//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace limonmali.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbLimonEntities : DbContext
    {
        public dbLimonEntities()
            : base("name=dbLimonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Slider> Slider { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Sayfalar> Sayfalar { get; set; }
    }
}
