//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace limonmali.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sayfalar
    {
        public int SayfaId { get; set; }
        public string SayfaAdi { get; set; }
        public string SayfaIcerik { get; set; }
        public string SayfaImg { get; set; }
        public Nullable<int> SayfaKatId { get; set; }
    
        public virtual Kategori Kategori { get; set; }
    }
}
