//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace limonmali.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int SliderId { get; set; }
        public string SliderAdi { get; set; }
        public string SliderIcerik { get; set; }
        public string SliderImg { get; set; }
    }
}
